### ISSUE TITLE
Allow camera to be configured to connect to an existing wireless router

### ISSUE THREAD

**Issue by steveluscher** [sepfy/xiaopi#1]
This image is great! Super simple, and useful.

One of the constraints imposed by making the Pi a wifi hotspot is that you can only connect to one camera at a time from a given host.

Have you considered creating the option to have the camera connect to an existing router on boot? This way, you could have many cameras join a single network, and aggregate all of them into a multi-view system.

**Comment by sepfy** [comment]
Hi! Sorry for the late reply and thanks for your advice. I am considering adding a simple web service to manage Pi's Wi-Fi connection. I will finish this work as soon as possible.

**Comment by sepfy** [comment]
I created an image to configure external router by web. Please check out the new image in [release page](https://github.com/sepfy/xiaopi/releases) and [wiki](https://github.com/sepfy/xiaopi/wiki/WiFi-Station). Thanks
